services:
  ros-noetic-tutorial:
    build: .
    user: root
    privileged: true
    container_name: ros-noetic-tutorial
    image: ros-noetic-tutorial
    tty: true
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  ros-noetic-tutorial-dev:
    build: .
    user: root
    privileged: true
    container_name: ros-noetic-tutorial-dev
    image: ros-noetic-tutorial-dev
    tty: true
    network_mode: host
    ipc: host
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ./catkin_ws/src:/catkin_ws/src
    profiles: ["dev"]
