services:
  ros2-humble-tutorial:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    container_name: ros2-humble-tutorial
    image: ros2-humble-tutorial
    tty: true
    network_mode: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  ros2-humble-tutorial-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    container_name: ros2-humble-tutorial-dev
    image: ros2-humble-tutorial-dev
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ../ros2_ws/src:/ros2_ws/src
    profiles: ["dev"]
